Repository zenml-io/zenml-projects, pull requests merged in 2025-03, with the labels that each got.

#173 Fix bug and formatting
  llm-complete-guide/constants.py
  llm-complete-guide/pipelines/llm_eval.py
  llm-complete-guide/pipelines/llm_langfuse_evals.py
  llm-complete-guide/run.py
  llm-complete-guide/steps/create_prompt.py
  llm-complete-guide/steps/eval_e2e.py
  llm-complete-guide/steps/eval_retrieval.py
  llm-complete-guide/steps/populate_index.py
  llm-complete-guide/steps/rag_deployment.py
  llm-complete-guide/utils/llm_utils.py
Labels: bug, internal

#174 Misc improvements
  llm-agents/README.md
  llm-complete-guide/deployment_hf.py
  llm-complete-guide/steps/eval_langfuse.py
Labels: enhancement, internal

#182 Fix research radar config
  .typos.toml
  research-radar/pipelines/classification.py
Labels: bug, internal

#185 Update Project listing presentation
  README.md
Labels: enhancement, internal

#175 Better visualization of the evaluation
  llm-complete-guide/ZENML_VERSION.txt
  llm-complete-guide/pipelines/llm_eval.py
  llm-complete-guide/steps/create_prompt.py
  llm-complete-guide/steps/eval_visualisation.py
Labels: enhancement, internal

#186 Formatting files
  databricks-production-qa-demo/steps/deployment/deployment_deploy.py
  end-to-end-computer-vision/steps/export_label_studio.py
  eurorate-predictor/pipelines/training.py
  eurorate-predictor/run.py
  gamesense/steps/finetune.py
  huggingface-sagemaker/steps/deploying/huggingface_deployment.py
  huggingface-sagemaker/steps/promotion/promote_get_metrics.py
  llm-complete-guide/pipelines/llm_eval.py
  llm-complete-guide/steps/create_prompt.py
  llm-complete-guide/steps/eval_retrieval.py
  llm-complete-guide/steps/eval_visualisation.py
  llm-complete-guide/steps/hf_dataset_loader.py
  llm-complete-guide/steps/url_scraper.py
  magic-photobooth/k8s_run.py
  magic-photobooth/modal_run.py
  magic-photobooth/modal_run_using_azure_data.py
  sign-language-detection-yolov5/steps/model_loader.py
  zencoder/run.py
  zencoder/steps/__init__.py
  zencoder/steps/deployment.py
  zencoder/steps/prepare_dataset.py
  zencoder/steps/push_dataset_to_hub.py
  zencoder/steps/trainer.py
  zencoder/steps/vllm_deployer.py
Labels: internal
