Repository zenml-io/zenml-projects, pull requests merged in 2025-05, with the labels that each got.

#203 add omni-reader project to table in README
  README.md
Labels: documentation, internal

#208 Fix README mismatches
  README.md
  huggingface-sagemaker/README.md
  magic-photobooth/README.md
  sign-language-detection-yolov5/README.md
Labels: documentation, internal, codex

#217 Add CI checks for formatting + clean up CI
  .github/workflows/code-formatting.yml
  .github/workflows/gpt4_summarizer.yml
  .github/workflows/production_run_complete_llm.yml
  .github/workflows/pull_request.yml
  .github/workflows/readme-projects-check.yml
  .github/workflows/staging_run_complete_llm.yml
  .gitignore
  CONTRIBUTING.md
  README.md
  databricks-production-qa-demo/steps/deployment/deployment_deploy.py
  gamesense/steps/log_metadata.py
  huggingface-sagemaker/steps/deploying/huggingface_deployment.py
  huggingface-sagemaker/steps/promotion/promote_get_metrics.py
  llm-complete-guide/steps/eval_retrieval.py
  llm-complete-guide/steps/hf_dataset_loader.py
  llm-complete-guide/steps/populate_index.py
  llm-complete-guide/utils/llm_utils.py
  magic-photobooth/frontend.py
  magic-photobooth/k8s_run.py
  magic-photobooth/modal_run.py
  magic-photobooth/modal_run_using_azure_data.py
  oncoclear/steps/model_promoter.py
  retail-forecast/pipelines/training_pipeline.py
  scripts/check-readme-projects.sh
  scripts/check_readme_projects.py
  scripts/format.sh
  sign-language-detection-yolov5/steps/model_loader.py
  vertex-registry-and-deployer/steps/model_promoter.py
  vertex-registry-and-deployer/steps/model_trainer.py
  zencoder/pipelines/generate_code_dataset.py
  zencoder/steps/deployment.py
  zencoder/test_starcoder_bigcode.py
  zencoder/test_zencoder.py
  zenml-support-agent/steps/agent_creator.py
Labels: enhancement, internal, CI/CD

#207 Improve root README
  README.md
Labels: documentation, internal, codex

#209 Add issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: codex

#211 Add missing dockerignore
  bank_subscription_prediction/.dockerignore
  huggingface-sagemaker/gradio/.dockerignore
  magic-photobooth/.dockerignore
  nightwatch-ai/.dockerignore
  retail-forecast/.dockerignore
  zenml-support-agent/.dockerignore
Labels: internal, codex

#210 Add missing type hints
  .github/PULL_REQUEST_TEMPLATE.md
  end-to-end-computer-vision/utils/dataset_utils.py
  llm-complete-guide/most_basic_rag_pipeline.py
  nightwatch-ai/src/pipelines/supabase_summary.py
  nightwatch-ai/src/run.py
  zencoder/steps/deployment.py
  zencoder/steps/trainer.py
Labels: enhancement, internal, codex
