Repository zenml-io/zenml-projects, pull requests merged in 2025-04, with the labels that each got.

#187 Add Omni Reader Project
  .typos.toml
  omni-reader/.dockerignore
  omni-reader/.env.example
  omni-reader/.gitignore
  omni-reader/LICENSE
  omni-reader/README.md
  omni-reader/app.py
  omni-reader/assets/docs/metrics.png
  omni-reader/assets/docs/pipeline_dags.png
  omni-reader/assets/docs/streamlit.png
  omni-reader/assets/docs/visualization.png
  omni-reader/assets/logos/default.svg
  omni-reader/assets/logos/gemma.svg
  omni-reader/assets/logos/microsoft.svg
  omni-reader/assets/logos/mistral.svg
  omni-reader/assets/logos/ollama.svg
  omni-reader/assets/logos/openai.svg
  omni-reader/assets/samples_for_ocr/easy_example.jpeg
  omni-reader/assets/samples_for_ocr/education_article_excerpt.webp
  omni-reader/assets/samples_for_ocr/incomplete_sentence.png
  omni-reader/assets/samples_for_ocr/lexus_vin_number.webp
  omni-reader/assets/samples_for_ocr/montreal_signs.jpg
  omni-reader/assets/samples_for_ocr/paris_signs.jpg
  omni-reader/assets/samples_for_ocr/reporter_notes.png
  omni-reader/assets/samples_for_ocr/rx_prescription_clear.jpg
  omni-reader/assets/samples_for_ocr/rx_prescription_unclear.png
  omni-reader/assets/samples_for_ocr/tire_serial_number.jpg
  omni-reader/configs/batch_pipeline.yaml
  omni-reader/configs/evaluation_pipeline.yaml
  omni-reader/ground_truth_texts/education_article_excerpt.txt
  omni-reader/ground_truth_texts/incomplete_sentence.txt
  omni-reader/ground_truth_texts/lexus_vin_number.txt
  omni-reader/ground_truth_texts/montreal_signs.txt
  omni-reader/ground_truth_texts/paris_signs.txt
  omni-reader/ground_truth_texts/reporter_notes.txt
  omni-reader/ground_truth_texts/rx_prescription_clear.txt
  omni-reader/ground_truth_texts/rx_prescription_unclear.txt
  omni-reader/ground_truth_texts/tire_serial_number.txt
  omni-reader/pipelines/__init__.py
  omni-reader/pipelines/batch_pipeline.py
  omni-reader/pipelines/evaluation_pipeline.py
  omni-reader/requirements.txt
  omni-reader/run.py
  omni-reader/schemas/__init__.py
  omni-reader/schemas/image_description.py
  omni-reader/schemas/ocr_result.py
  omni-reader/steps/__init__.py
  omni-reader/steps/evaluate_models.py
  omni-reader/steps/loaders.py
  omni-reader/steps/run_ocr.py
  omni-reader/utils/__init__.py
  omni-reader/utils/config.py
  omni-reader/utils/encode_image.py
  omni-reader/utils/extract_json.py
  omni-reader/utils/metrics.py
  omni-reader/utils/model_configs.py
  omni-reader/utils/ocr_processing.py
  omni-reader/utils/prompt.py
  omni-reader/utils/visualizations.py
Labels: enhancement, internal

#189 Fix DataFrame structure inconsistency between single and multi-model OCR runs
  omni-reader/README.md
  omni-reader/assets/docs/pipeline_dags.png
  omni-reader/assets/samples_for_ocr/handwritten/easy_example.jpeg
  omni-reader/assets/samples_for_ocr/handwritten/education_article_excerpt.webp
  omni-reader/assets/samples_for_ocr/handwritten/incomplete_sentence.png
  omni-reader/assets/samples_for_ocr/handwritten/reporter_notes.png
  omni-reader/assets/samples_for_ocr/numbers/lexus_vin_number.webp
  omni-reader/assets/samples_for_ocr/numbers/tire_serial_number.jpg
  omni-reader/assets/samples_for_ocr/rx_prescriptions/rx_prescription_clear.jpg
  omni-reader/assets/samples_for_ocr/rx_prescriptions/rx_prescription_unclear.png
  omni-reader/assets/samples_for_ocr/street_signs/montreal_signs.jpg
  omni-reader/assets/samples_for_ocr/street_signs/paris_signs.jpg
  omni-reader/configs/batch_pipeline.yaml
  omni-reader/configs/evaluation_pipeline.yaml
  omni-reader/pipelines/batch_pipeline.py
  omni-reader/pipelines/evaluation_pipeline.py
  omni-reader/steps/evaluate_models.py
  omni-reader/steps/loaders.py
  omni-reader/utils/visualizations.py
Labels: enhancement

#190 Add Dockerfile for running OmniReader in sandbox environment
  omni-reader/Dockerfile.sandbox
  omni-reader/settings.json
Labels: enhancement

#197 Add oncoclear to README
  README.md
Labels: documentation, internal

#196 Add sandbox dockerfile generator script
  .github/workflows/build-push-codespace.yml
  generate_zenml_project.py
  omni-reader/Dockerfile.codespace
  omni-reader/Dockerfile.sandbox
  oncoclear/Dockerfile.codespace
  pyproject.toml
  scripts/generate_codespace_dockerfile.py
Labels: enhancement, internal

#198 Fix "no match for platform" GH action failure
  .github/workflows/build-push-codespace.yml
Labels: CI/CD

#201 chore: update README.md of zenml-support-agent to correct installation path
  zenml-support-agent/README.md
Labels: documentation
